accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
]

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='list'),
    path('create/', views.PostCreate.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='byuser'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.PostDelete.as_view(), name='delete'),
]

redzitta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('subs/', include('subs.urls')),
    path('posts/', include('posts.urls')),
]

subs/urls.py
from . import views
from django.urls import path

app_name = 'subs'

urlpatterns = [
    path('', views.SubList.as_view(), name='list'),
    path('create/', views.SubCreate.as_view(), name='create'),
    path('detail/<slug:slug>/', views.SubDetail.as_view(), name='detail'),
    path('join/<slug:slug>/', views.SubJoin.as_view(), name='join'),
    path('leave/<slug:slug>', views.SubLeave.as_view(), name='leave'),
]

accounts/models.py
from django.db import models
from django.contrib import auth

class User(auth.models.User):

    class Meta:
        proxy = True

    def __str__(self):
        return "@{}".format(self.email)

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

import misaka

from subs.models import Sub

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    sub = models.ForeignKey(Sub, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        constraints = [
            models.UniqueConstraint(fields=['user', 'sub', 'message'], name='user_message'),
        ]

subs/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model
from django import template

import misaka

User = get_user_model()
register = template.Library()

class Sub(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(blank=True, editable=False, default='')
    members = models.ManyToManyField(User, through='SubMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('subs:detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class SubMember(models.Model):
    sub = models.ForeignKey(Sub, related_name='sub_members', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_subs', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['sub', 'user'], name='unique_membership'),
        ]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as BaseCreationForm

class UserCreationForm(BaseCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['username'].label = 'Display Name'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .import forms

class SignUp(CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'home/index.html'

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.http import Http404
from django.contrib import messages
from django.contrib.auth import get_user_model
User = get_user_model()

from . import models

class PostList(ListView):
    model = models.Post

class UserPosts(ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(DetailView):
    model = models.Post

class PostDelete(DeleteView):
    model = models.Post

class PostCreate(LoginRequiredMixin, CreateView):
    fields = ['message', 'sub']
    model = models.Post

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostDelete(LoginRequiredMixin, DeleteView):
    model = models.Post
    success_url = reverse_lazy('posts:list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

subs/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    )
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.contrib import messages

from .models import Sub, SubMember

class SubCreate(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Sub

class SubDetail(generic.DetailView):
    model = Sub

class SubList(generic.ListView):
    model = Sub

class SubJoin(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('subs:detail', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        sub = get_object_or_404(Sub, slug=self.kwargs.get('slug'))
        try:
            SubMember.objects.create(user=self.request.user, sub=sub)
        except IntegrityError:
            messages.warning(self.request, 'Warning already a member!')
        else:
            messages.success(self.request, 'You are now a member!')
        return super().get(request, *args, **kwargs)

class SubLeave(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('subs:detail', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = SubMember.objects.filter(user=self.request.user, sub__slug=self.kwargs.get('slug')).get()
        except SubMember.DoesNotExist:
            messages.warning(self.request, 'Sorry, you are not in this Sub.')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the sub!')
        return super().get(request, *args, **kwargs)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="container">
    <h1>Log In</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Log In">
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Sign Up">
    </form>
  </div>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to Redzitta!</h1>
{% endblock %}

posts/templates/posts/_post.html
<div class="post media">
  <h3>{{ post.message_html|safe }}</h3>
  <div class="media-body">
    <h5 class="media-heading"></h5>
    <span class="username">
      <a href="{% url 'posts:byuser' username=post.user.username %}">{{ post.user }}</a>
    </span>
    <time class="time">
      <a href="{% url 'posts:detail' pk=post.pk %}"></a>
    </time>

    <div class="media-footer">
      {% if user.is_authenticated and post.user == user and not hide_delete %}
        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}

  <div class="post-page">
    <div class="container">
      <div class="row">
        {% block prepost %}{% endblock %}
        {% block post_content %}{% endblock %}
        {% block postpost %}{% endblock %}
      </div>
    </div>
  </div>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <h3>Are you sure you want to delete this post?</h3>
  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>

  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger">
    <a href="{% url 'posts:detail' pk=object.pk %}" class="btn btn-simple">Cancel</a>
  </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <div class="col-md-8">
    {% include "posts/_post.html" %}
  </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}

{% block post_content %}
  <h4>Create a New Post</h4>
  <form id="post-form" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class="btn btn-primary">
  </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title">Your Subs</h5>
          <ul class="list-unstyled">
            {% for member_sub in get_user_subs %}
              <li class="sub-li li-with-bullet">
                <a href="{% url 'subs:detail' slug=member_sub.sub.slug %}">{{ member_sub.sub }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endif %}
    <div class="car card-with-shadow">
      <div class="content">
        <h5 class="title">All Subs</h5>
        <ul class="list-unstyled">
          {% for other_sub in get_other_sub %}
            <li class="sub-li li-with-bullet">
              <a href="{% url 'subs:detail' slug=other_sub.sub.slug %}">{{ other_sub.sub }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
  <div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}

subs/templates/subs/sub_base.html
{% extends 'base.html' %}
{% block content %}

  <div class="container">
      {% block presub %}{% endblock %}
      {% block sub_content %}{% endblock %}
      {% block postsub %}{% endblock %}
  </div>
  
{% endblock %}

subs/templates/subs/sub_detail.html
{% extends 'subs/sub_base.html' %}
{% block presub %}

  <h1>{{ sub.name }}</h1>
  <h2>Member Count: {{ sub.members.count }}</h2>

  <div class="content">
    {% if user in sub.members.all %}
      <a href="{% url 'subs:leave' slug=sub.slug %}" class="btn btn-warning">Leave</a>
    {% else %}
      <a href="{% url 'subs:join' slug=sub.slug %}" class="btn btn-primary">Join</a>
    {% endif %}
  </div>

{% endblock %}

{% block sub_content %}

  {% if sub.posts.count == 0 %}
    <h2>Members in this sub are quite lazy. There aren't any posts yet.</h2>
  {% else %}
    {% for post in sub.posts.all %}
      {% include 'posts/_post.html' %}
    {% endfor %}
  {% endif %}

{% endblock %}

subs/templates/subs/sub_form.html
{% extends 'subs/sub_base.html' %}
{% load bootstrap4 %}

{% block sub_content %}
  <h4>Create a new sub</h4>

  <form method="POST" id="sub_form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">Create!</button>
  </form>
{% endblock %}

subs/templates/subs/sub_list.html
{% extends 'subs/sub_base.html' %}

{% block presub %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2>
          <a href="{% url 'posts:byuser' username=user.username %}">
            @{{ user.username }}
          </a>
        </h2>
      {% endif %}
      <h2>Subs</h2>
    </div>
    {% if user.is_authenticated %}
      <a href="{% url 'subs:create' %}" class="btn btn-primary"><span class="iconify" data-icon="whh:plussign" data-inline="false"></span></a>
    {% endif %}
  </div>
{% endblock %}

{% block sub_content %}
  <div class="col-md-8">
    <div class="sub-list">
      {% for sub in object_list %}
        <a class="sub-list-item" href="{% url 'subs:detail' slug=sub.slug %}">
          <h3 class="title sub-list-item-heading">{{ sub.name }}</h3>
          <div class="sub-list-item-text container-fluid">
            {{ sub.description_html|safe }}
            <div class="row">
              <div class="col-md-4">
                <span class="badge">{{ sub.members.count }}</span>
                member{{ sub.members.count|pluralize }}
              </div>
              <div class="col-md-4">
                <span class="badge">{{ sub.posts.count }}</span>
                post{{ sub.posts.count|pluralize }}
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>redzitta</title>

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Medium Style Editer -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Limelight&display=swap" rel="stylesheet">

    <!-- Iconify -->
    <script src="https://code.iconify.design/1/1.0.3/iconify.min.js"></script>

  </head>
  <body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light techfont custom-navbar">
      <a class="navbar-brand bigbrand" href="{% url 'home' %}">rdt/</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <!-- <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="#">link 1</a></li>
          <li class="nav-item"><a class="nav-link" href="#">link 2</a></li>
          <li class="nav-item"><a class="nav-link" href="#">link 3</a></li>
        </ul> -->
        {% if user.is_authenticated %}
          <span class="navbar-text welcome-user ml-auto">
            {{ user }}
          </span>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'subs:list' %}">Subs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'subs:create' %}">Create a Sub</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
          </ul>
        {% endif %}
      </div>
    </nav>

    {% block content %}
    {% endblock %}
  </body>
</html>